import type { Metadata } from "next";
import { Poppins } from 'next/font/google';
import "./globals.css";



const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '700'],  // Puedes elegir los pesos que necesites
  variable: '--font-poppins',  // Variable CSS para uso global
  display: 'swap',  // Optimización recomendada
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={poppins.variable}
      >

        {children}

      </body>
    </html>
  );
}
